# Generated by Django 3.2.7 on 2022-05-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('study', models.CharField(max_length=100)),
                ('YOP', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('CGPA', models.CharField(max_length=50)),
                ('College', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('Interest', models.CharField(max_length=500)),
            ],
        ),
    ]
