# Generated by Django 3.2.7 on 2022-05-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basewebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('qual', models.CharField(max_length=100)),
                ('pnumber', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=500)),
            ],
        ),
    ]
