# Generated by Django 3.2.7 on 2022-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('tutorname', models.CharField(max_length=100)),
                ('studentname', models.CharField(max_length=100)),
                ('dateofthesession', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=100)),
                ('totalduration', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('expectation', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherdetails',
            name='user_details',
        ),
    ]
